poses:
  - x: -20.0
    y: 5.0
    yaw: 0.0
  # - x: 32.11
  #   y: -35.11
  #   yaw: -0.64
  # - x: 73.34
  #   y: -72.74
  #   yaw: 0.66
  # - x: 43.19
  #   y: -15.19
  #   yaw: -0.52
  # - x: 20.75
  #   y: -9.07
  #   yaw: 0.52
